SELECT USER
FROM DUAL;
--==>> NO1

-- 오류 메시지 목록
/*
-20001, '데이터 중복'
-20002, '데이터 없음'
-20003, '유효하지 않은 데이터'
*/


--------------------------------------------------------------------------------
-- PRC_TEXTBOOK_INSERT----------------------------------------------------------

CREATE OR REPLACE PROCEDURE PRC_TEXTBOOK_INSERT
(
  V_BOOK_NAME   IN TBL_TEXTBOOK.BOOK_NAME%TYPE
, V_BOOK_PUB    IN TBL_TEXTBOOK.BOOK_PUB%TYPE 
)
IS
    V_BOOK_CODE     TBL_BOOK.BOOK_CODE%TYPE;
    USER_DEFINE_ERROR   EXCEPTION;
BEGIN

    SELECT BOOK_CODE INTO V_BOOK_CODE
    FROM TBL_TEXTBOOK
    WHERE BOOK_NAME = V_BOOK_NAME;
    
    IF (BOOK_CODE IS NULL)   
        THEN RAISE USER_DEFINE_ERROR;
    END IF;
    
    INSERT INTO TBL_TEXTBOOK(BOOK_CODE, BOOK_NAME, BOOK_PUB)
    VALUES(TBL_TEXTBOOK_SEQ.NEXTVAL, V_BOOK_NAME, V_BOOK_PUB);
    
    EXCEPTION
        WHEN USER_DEFINE_ERROR
            THEN RAISE_APPLICATION_ERROR(-20001, '데이터 중복');
        WHEN OTHERS
            THEN ROLLBACK;
            
    COMMIT;
    
END;

--------------------------------------------------------------------------------
-- PRC_OCLASS_INSERT------------------------------------------------------------

CREATE OR REPLACE PROCEDURE PRC_OCLASS_INSERT
(
  V_PRO_ID        IN TBL_ABLE.PRO_ID%TYPE
, V_CLASS_CODE    IN TBL_OCLASS.CLASS_CODE%TYPE
, V_START_DATE    IN TBL_OCLASS.START_DATE%TYPE  
, V_END_DATE      IN TBL_OCLASS.END_DATE%TYPE
, V_INSERT_DATE   IN TBL_OCLASS.INSERT_DATE%TYPE
)
IS
    V_ABLE_CODE     TBL_ABLE.ABLE_CODE%TYPE;
    V_OCOURSE_CODE  TBL_OCOURSE.OCOURSE_CODE%TYPE;
    V_BOOK_CODE     TBL_TEXTBOOK.BOOK_CODE%TYPE;
BEGIN
    SELECT ABLE_CODE INTO V_ABLE_CODE
    FROM TBL_ABLE
    WHERE PRO_ID = V_PRO_ID
      AND CLASS_CODE = V_CLASS_ID;
      
    INSERT INTO TBL_OCLASS(START_DATE, END_DATE, INSERT_DATE
                            , ABLE_CODE, OCOURSE_CODE, BOOK_CODE)
    VALUES(TBL_OCLASS_SEQ.NEXTVAL, V_START_DATE, V_END_DATE, V_INSERT_DATE
            , V_ABLE_CODE, V_OCOURSE_CODE, V_BOOK_CODE);
            
    COMMIT;
END;

--------------------------------------------------------------------------------
-- PRC_POINT_INSERT-------------------------------------------------------------

CREATE OR REPLACE PROCEDURE PRC_POINT_INSERT
(
  V_POINT_CODE        IN TBL_POINT.POINT_CODE%TYPE
, V_POINT_ATTEND      IN TBL_POINT.POINT_ATTEND%TYPE
, V_POINT_PRACTICE    IN TBL_POINT.POINT_PRACTICE%TYPE
, V_POINT_WRITE       IN TBL_POINT.POINT_WRITE%TYPE
)
IS
    V_OCLASS_CODE   TBL_OCLASS.OCLASS_CODE%TYPE;
BEGIN
    
    SELECT OCLASS_CODE INTO V_OCLASS_CODE
    FROM TBL_OCLASS
    WHERE OCLASS_CODE = V_OCLASS_CODE;
    
    
    
END;
